name: Format Auto Review

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    paths:
      - '**/*.md'

permissions:
  checks: write
  contents: read
  pull-requests: write

concurrency: ci-${{ github.workflow }}-${{ github.ref }}

jobs:
  auto-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.3.2
        with:
          reviewdog_version: latest
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: '**/*.md'

      - name: Running autocorrect
        continue-on-error: true
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sSL https://git.io/JcGER | sh
          autocorrect --lint --format rdjson ${{ steps.changed-files.outputs.all_changed_files }} | \
            reviewdog -f=rdjson -level=warning -reporter=github-pr-review -fail-level=warning
      - name: Running markdownlint
        uses: reviewdog/action-markdownlint@v0.26.2
        continue-on-error: true
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          markdownlint_flags: ${{ steps.changed-files.outputs.all_changed_files }}
          fail_level: error
      - name: Post comment
        uses: thollander/actions-comment-pull-request@v3
        if: failure()
        with:
          message: |
            源码格式/语法检查未通过，请根据 GitHub Action 给出的 Code Review 审查建议进行修改。

            对于有争议的修改建议，可暂时不进行修改并在 PR 中进行讨论。

            > 注：可通过 "Files changed" 页面中的 "Add suggestion to batch" 功能来批量采纳修改建议。

      # - name: Check punctuation
      #   if: steps.changed-files.outputs.any_changed == 'true'
      #   id: punctuation-check
      #   env:
      #     GITHUB_URL: ${{ github.event.pull_request.head.repo.clone_url }}
      #     GITHUB_REF: ${{ github.event.pull_request.head.ref }}
      #   run: |
      #     python tools/punctuation_checker.py \
      #            "${{ steps.changed-files.outputs.all_changed_files }}"
      # - name: Comment PR
      #   if: steps.changed-files.outputs.any_changed == 'true'
      #   uses: thollander/actions-comment-pull-request@v3
      #   with:
      #     file-path: results.txt
      #     comment-tag: punctuation-check
